"""
Application-wide configuration settings.
"""

# Camera
CAMERA_INDEX: int = 0
CAMERA_WIDTH: int = 1280
CAMERA_HEIGHT: int = 720

# Object detection
PERSON_CLASS_ID: int = 0

# Pose estimation
POSE_MIN_VISIBILITY = 0.5

# Pose estimation intervals
POSE_INTERVAL_SINGLE_PERSON: int = 2
POSE_INTERVAL_FEW_PEOPLE: int = 3
POSE_INTERVAL_MANY_PEOPLE: int = 4

# Landmark estimation
POSE_MIN_VISIBLE_LANDMARKS = 15

# Minimum size required before running pose estimation
MIN_PERSON_WIDTH: int = 120
MIN_PERSON_HEIGHT: int = 200

# Tracking
TRACK_PERSIST: bool = True
TRACK_CONFIDENCE_THRESHOLD = 0.35

# Risk estimation
PROXIMITY_START_DISTANCE = 800.0
PROXIMITY_FULL_RISK_DISTANCE = 300.0
PROXIMITY_RISK_WEIGHT = 0.20

# Body movement risk
BODY_MOVEMENT_MIN_SPEED = 20.0
BODY_MOVEMENT_MAX_SPEED = 80.0
BODY_MOVEMENT_RISK_WEIGHT = 0.15

# Risk persistence
RISK_INCREASE_MEMORY = 0.30
RISK_DECREASE_MEMORY = 0.85


POSE_CACHE_TIMEOUT = 0.5

# Hand movement risk
HAND_SPEED_MAX_PIXELS = 250.0
HAND_SPEED_FULL_RISK = 140.0
HAND_SPEED_MIN_SPEED = 30.0
HAND_SPEED_MAX_SCORE = 0.15

# Arm Extension Risk
ARM_EXTENSION_START_RATIO = 0.80
ARM_EXTENSION_FULL_RATIO = 0.98
ARM_EXTENSION_MAX_SCORE = 0.15
ARM_EXTENSION_HAND_SPEED_GATE = 0.05

# Approach Speed Risk
APPROACH_SPEED_START = 20.0
APPROACH_SPEED_FULL = 100.0
APPROACH_SPEED_MAX_SCORE = 0.20

# Escalation Persistence
ESCALATION_BUILD_RATE = 0.08
ESCALATION_DECAY_RATE = 0.04
ESCALATION_DECAY_THRESHOLD = 0.20
ESCALATION_CONFIDENCE_WEIGHT = 0.20