"""Validated defaults for the research prototype.

Values are intentionally conservative and configurable from the command line.
Risk is an explainable heuristic score, not a probability of violence.
"""

# Capture
CAMERA_INDEX = 0
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720

# Detection / tracking
PERSON_CLASS_ID = 0
TRACK_PERSIST = True
TRACK_CONFIDENCE_THRESHOLD = 0.35
YOLO_MODEL = "yolov8n.pt"

# Pose
POSE_MIN_VISIBILITY = 0.50
POSE_MIN_VISIBLE_LANDMARKS = 15
POSE_INTERVAL_SINGLE_PERSON = 2
POSE_INTERVAL_FEW_PEOPLE = 3
POSE_INTERVAL_MANY_PEOPLE = 4
POSE_CACHE_TIMEOUT = 0.50
MIN_PERSON_WIDTH = 80
MIN_PERSON_HEIGHT = 140

# Explainable risk features. Distances and speeds are normalized by person height.
PROXIMITY_START_RATIO = 1.80
PROXIMITY_FULL_RISK_RATIO = 0.55
PROXIMITY_MAX_SCORE = 0.18
APPROACH_SPEED_START = 0.15       # person-heights / second
APPROACH_SPEED_FULL = 1.00
APPROACH_SPEED_MAX_SCORE = 0.16
BODY_MOVEMENT_MIN_SPEED = 0.15    # person-heights / second
BODY_MOVEMENT_MAX_SPEED = 1.20
BODY_MOVEMENT_MAX_SCORE = 0.14
HAND_SPEED_MIN_SPEED = 0.40       # person-heights / second
HAND_SPEED_FULL_RISK = 2.40
HAND_SPEED_MAX_SCORE = 0.14
ARM_EXTENSION_START_RATIO = 0.80
ARM_EXTENSION_FULL_RATIO = 0.98
ARM_EXTENSION_MAX_SCORE = 0.10
ARM_EXTENSION_HAND_SPEED_GATE = 0.02
INTERACTION_DISTANCE_RATIO = 1.20
INTERACTION_DURATION_START = 1.0
INTERACTION_DURATION_FULL = 5.0
INTERACTION_DURATION_MAX_SCORE = 0.12
MULTI_CUE_BONUS = 0.10

# Time-aware score smoothing
RISK_RISE_TAU_SECONDS = 0.35
RISK_FALL_TAU_SECONDS = 1.80
MAX_DELTA_SECONDS = 0.50
STATE_TTL_SECONDS = 2.0

# Alert levels and hysteresis
WATCH_THRESHOLD = 0.25
WARNING_THRESHOLD = 0.50
CRITICAL_THRESHOLD = 0.75
ALERT_HYSTERESIS = 0.07
WATCH_CONFIRMATION_TIME = 1.5
WARNING_CONFIRMATION_TIME = 1.25
CRITICAL_CONFIRMATION_TIME = 0.75

# Display
WINDOW_NAME = "AI Escalation Predictor — Research Prototype"
